### ISSUE TITLE
glibc integration

### ISSUE THREAD

**Issue by HulaHoop0** [GrapheneOS/hardened_malloc#102]
We're trying to get glibc and indirectly Debian to adopt hardened_malloc so it sees system wide testing/breakage fixing with incompatible apps and hopefully more widespread adoption.

Their main gripe is h_malloc is 64-bit only and there are no published perf benchmarks comparing it with other hardened allocators like Scudo

https://sourceware.org/ml/libc-alpha/2019-11/msg00813.html

PS. What is your opinion about Scudo?

cc/ @adrelanos

**Comment by thestinger** [comment]
Scudo's design isn't nearly as hardened and a lot more of it can be trivially bypassed due to being based on inline metadata with weak probabilistic protections. It's not the same thing. Both allocators referring to themselves as hardened doesn't make them comparable.

**Comment by thestinger** [comment]
> Their main gripe is h_malloc is 64-bit only

The design is entirely based around the 64-bit address space and it's not possible for it to support 32-bit. Even if it wasn't inherently incompatible with the design, it wouldn't make sense since it's outside the scope of the project. GrapheneOS uses hardened_malloc and others are welcome to use it but I won't push them to do it. I don't really care about glibc or Debian. I'm not interested in their misunderstandings, uninformed criticism and FUD either.

**Comment by adrelanos** [comment]
chromium feature request: `consider using hardened malloc`
https://bugs.chromium.org/p/chromium/issues/detail?id=1204783
