### ISSUE TITLE
Upstream Firefox bug: invalid uninitialized allocator usage

### ISSUE THREAD

**Issue by cyanlemons** [GrapheneOS/hardened_malloc#123]
This isn't an issue with hardened_malloc, but it may be useful to document [this upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1668674) here for visibility purposes. When running Firefox with hardened_malloc, occasionally I will come across a webpage that will crash the tab and print the following in my terminal (if verbose outputs are turned on):
```
fatal allocator error: invalid uninitialized allocator usage
Redirecting call to abort() to mozalloc_abort
```

**Comment by thestinger** [comment]
This message comes from the `enforce_init` function. This is used to detect attempts to free allocations before there have been any allocations. The hardened_malloc implementation tries to initialize itself early on via a constructor with the highest possible priority permitted for a non-libc component, so it's very strange to have code running before it in the first place. Firefox must be doing something quite strange to be ending up in this situation for multiple reasons.

**Comment by thestinger** [comment]
I don't think there's much chance that this is a hardened_malloc bug, but it's probably not simply a memory corruption bug in Firefox. It's some kind of more complex issue like Firefox attempting to mix different malloc implementations such as by not completely replacing all of the symbols. It sounds like the issue occurs after early initialization (although maybe this happens in a freshly spawned process) so that makes it seem like hardened_malloc is not really being used until some point where it ends up calling into a function like `malloc_usable_size` that passes through to hardened_malloc instead of their incomplete overrides of the symbols. I'm not really sure what's happening.

For now though, I'm going to close this issue since I don't think it's a hardened_malloc issue. Even without the constructor to initialize hardened_malloc early, it works properly. That constructor is optional and just intended to reduce the chances that the address space has already been heavily fragmented, etc. before hardened_malloc tries to reserve a massive portion of it as PROT_NONE mappings.
