### ISSUE TITLE
Correct way to build into libc?

### ISSUE THREAD

**Issue by sempervictus** [GrapheneOS/hardened_malloc#130]
We use Arch and have a variant of the AUR package tracking the git repo via jenkins to keep building a tip package when master is updated (the chroot build is separate from dependency acquisition, to reduce pwnage from repos and aur sneaking in). At present, the package is setup to force LD_PRELOAD for everything as a system-wide configuration, but LD_PRELOAD doesn't always work how we would want - some binries still end up using libc's allocator.
Since we're not redistributing our packages, it occurs to me that building the allocator right into libc to replace its own malloc, and then packaging that should maintain ABI with the rest of userspace since its just the Arch stable package rebuilt, and address the edge-cases for preload.
Whats the correct way of doing something like this? Correct being defined as "the most efficient and compatible."
Thanks as always

**Comment by thestinger** [comment]
You should patch the libc implementation so that it calls into hardened_malloc on 64-bit instead of using their own malloc implementation. In Bionic, the libc implementation is already designed to support different allocators so it's very easy for us to do this:

https://github.com/GrapheneOS/platform_bionic/commit/a9d4f262bdf4f94fba0c608e218a30f0e4c167e8#diff-7dec5941e3915083d4257ba51ae9769677fdc622b7bbd2cfd3c6266ccab8d75e

**Comment by thestinger** [comment]
The easiest way to do it is to compile hardened_malloc as a static library with the `h_` prefix and link it into libc. Then, add calls into hardened_malloc instead of their own malloc implementation.

Bionic has infrastructure for malloc debugging, malloc memory limits, etc. which is implemented by setting up a function pointer table with the correct functions during initialization. The table is inside the `__libc_globals` data that's made read-only after early initialization. That's why it's so trivial for us to implement this for Bionic.

Most malloc implementations won't have that extra layer of indirection, and it would be ever so slightly more efficient to build hardened_malloc without a prefix and instead conditionally omit the libc malloc implementation and link in the hardened_malloc implementation instead. This requires that the symbols are defined exactly the way that the libc sets it up which we definitely aren't doing right now and aren't really interested in doing. It's the responsibility of whoever is integrating it into the libc. So for example, certain symbols need to be weak and implemented in certain ways, etc. It's simpler to have a layer of indirection and simply call the `h_` prefixed functions from their existing implementation. That avoids needing to make a mess in hardened_malloc to match what glibc does. It would be easier to do for musl and we'd probably accept the changes for it upstream.
