### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by berkley4** [GrapheneOS/hardened_malloc#136]
Using Debian amd64 and building with clang/lld version 13.....

CPPFLAGS='-D_FORTIFY_SOURCE=2' make CONFIG_NATIVE=true CC=clang CONFIG_SLAB_QUARANTINE_RANDOM_LENGTH=0 CONFIG_SLAB_QUARANTINE_QUEUE_LENGTH=0
.
.
.
clang  -std=c++14 -O3 -flto -fPIC -fvisibility=hidden -fno-plt -fstack-clash-protection -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align -Wcast-qual -Wwrite-strings -Wno-constant-logical-operand -Werror -march=native -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I include -DCONFIG_SEAL_METADATA=false -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=0 -DSLAB_QUARANTINE_QUEUE_LENGTH=0 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=256 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o new.o new.cc

new.cc:113:45: error: no type named 'align_val_t' in namespace 'std'
EXPORT void *operator new(size_t size, std::align_val_t alignment) {
                                       ~~~~~^
new.cc:117:47: error: no type named 'align_val_t' in namespace 'std'
EXPORT void *operator new[](size_t size, std::align_val_t alignment) {
                                         ~~~~~^
new.cc:121:45: error: no type named 'align_val_t' in namespace 'std'
EXPORT void *operator new(size_t size, std::align_val_t alignment, const std::nothrow_t &) noexcept {
                                       ~~~~~^
new.cc:125:47: error: no type named 'align_val_t' in namespace 'std'
EXPORT void *operator new[](size_t size, std::align_val_t alignment, const std::nothrow_t &) noexcept {
                                         ~~~~~^
new.cc:129:45: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete(void *ptr, std::align_val_t) noexcept {
                                       ~~~~~^
new.cc:133:47: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete[](void *ptr, std::align_val_t) noexcept {
                                         ~~~~~^
new.cc:137:45: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete(void *ptr, std::align_val_t, const std::nothrow_t &) noexcept {
                                       ~~~~~^
new.cc:141:47: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete[](void *ptr, std::align_val_t, const std::nothrow_t &) noexcept {
                                         ~~~~~^
new.cc:145:58: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete(void *ptr, size_t size, std::align_val_t) noexcept {
                                                    ~~~~~^
new.cc:149:60: error: no type named 'align_val_t' in namespace 'std'
EXPORT void operator delete[](void *ptr, size_t size, std::align_val_t) noexcept {
                                                      ~~~~~^
10 errors generated.
make: *** [<builtin>: new.o] Error 1

.
A quick google seemed to indicate that align_val_t was introduced with C++17. I'm not sure if this is the correct fix, but editing the Makefile as below had the effect of using -std=c++17 instead of -std=c++14, and building without error.

 CFLAGS := $(CFLAGS) -std=c11 $(SHARED_FLAGS) -Wmissing-prototypes
-CXXFLAGS := $(CXXFLAGS) $(call safe_flag,-std=c++17,-std=c++14) $(SHARED_FLAGS)
+CXXFLAGS := $(CXXFLAGS) $(call safe_flag,-std=c++14,-std=c++17) $(SHARED_FLAGS)
 LDFLAGS := $(LDFLAGS) -Wl,--as-needed,-z,defs,-z,relro,-z,now,-z,nodlopen,-z,text

**Comment by thestinger** [comment]
Support for legacy C++ versions was dropped in https://github.com/GrapheneOS/hardened_malloc/commit/e0ecacff451912a32a1a63f9d9a8d7f63546cfd8 to simplify the code.

You can build with `CONFIG_CXX_ALLOCATOR=false` if you don't have C++17 support. The only thing you lose is sanity checking the sized deallocation size. C++ added sized deallocation in C++14 and the size is often passed for things based on C++ standard library abstractions. It's useful for checking that the object is what the process thinks it is and it can catch type confusion bugs, etc. in some cases. It's usually too late for it to stop exploitation of these bugs so it's not seen as particularly important / useful just an extra frill. GrapheneOS doesn't use it yet due to compatibility issues with broken programs passing invalid sizes.

**Comment by thestinger** [comment]
It's the standard library that's the issue, not the compiler.

**Comment by thestinger** [comment]
I assumed that since C++17 features have been implemented for a long time that I could get away with dropping the conditional usage at this point. I guess libstdc++ had a very late implementation of this feature and Debian stable has a ridiculously old version of it. Maybe I just won't support Debian anymore. That stuff is too old and they are NOT actually backporting most of the security fixes as they lead people to believe, only a subset of the small fraction of security fixes with a CVE assignment. Debian isn't a good or secure base for anything serious. Probably no point in hardened_malloc going through the effort of supporting it. We no longer use it on any servers, etc. or test it.
