### ISSUE TITLE
add safe-unlinking to double-lists

### ISSUE THREAD

**Issue by jvoisin** [GrapheneOS/hardened_malloc#168]
There are a couple of double-linked lists in the codebase, and it would be nice to add safe-unlinking checks to them I think.

**Comment by thestinger** [comment]
The metadata is entirely contained within an isolated region with a high entropy random base so I don't think there's a point in adding sanity checks for it. It can optionally be protected by MPK on x86 but MPK turned out to be fairly high overhead. On ARM64, it's going to be protected by memory tagging once that's implemented / available.

**Comment by thestinger** [comment]
Those doubly-linked lists are also simply mixed in with all the other out-of-line metadata. The approach is having all of the metadata entirely out-of-line and isolated with the ability to apply protections like MPK and memory tagging as a further overkill step. It isn't vulnerable to any traditional allocator attacks since the only thing inline are the optional canaries which don't store any metadata (although they *could* be used to store something like tiny type hashes for an additional security feature).
