### ISSUE TITLE
Pycharm crashes with using libhardened_malloc

### ISSUE THREAD

**Issue by sydhds** [GrapheneOS/hardened_malloc#208]
Trying to run pycharm (installed via snap repo, using classic mode) on ubuntu 22.10 with libhardened_malloc produces the following error: 

```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGABRT (0x6) at pc=0x00007ff14d69226b (sent by kill), pid=4305, tid=4502
#
# JRE version: OpenJDK Runtime Environment JBR-17.0.5+1-653.23-jcef (17.0.5+1) (build 17.0.5+1-b653.23)
# Java VM: OpenJDK 64-Bit Server VM JBR-17.0.5+1-653.23-jcef (17.0.5+1-b653.23, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x9226b]  pthread_kill+0x11b
#
```

Pycharm version: pycharm-community 2022.3.1 (classic mode)
I've tried with default version and light version (using the latest version in master)  and the results looks the same.

If you are interested I can provide a full log provided I can send it by email.

**Comment by thestinger** [comment]
The process is killing itself with pthread_kill which isn't used by hardened_malloc. More information would be required to even guess at what the problem could be. It's almost certainly a bug in this application or one of the many libraries it uses. It could be a bug in the version of OpenJDK. It's more likely a bug in a library. More information on architecture, etc. would be helpful along with a full traceback rather than just a single location of where the signal was received.

**Comment by thestinger** [comment]
> If you are interested I can provide a full log provided I can send it by email.

Please do that, maybe there's some more information. contact@grapheneos.org is fine.
