### ISSUE TITLE
Is this still maintained for Linux (non-Android)?

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#214]
Usually there have been tags such as `9`, `10`, `11`.

Tag `12` is missing.

There is also not tag `13`.

There closest thing I found was tag `13-qpr1`. Is this tag also supposed to be usable on Linux, i.e. not on Android?

**Comment by thestinger** [comment]
It's still maintained. There have not been many changes recently since the project is mature and we haven't had the resources to dedicate to adding any of the major planned enhancements to it. In particular, we want to add hardware memory tagging support. We also want to reduce the memory overhead of slab quarantines in the default configuration by making them smaller and perhaps adding purging of mixed quarantined/free slot slabs instead of only fully free slabs. Other enhancements are also wanted. No one is contributing and we don't have enough developers.

**Comment by thestinger** [comment]
There are no known bugs and not much more low-hanging micro-optimization or tuning to do without making difficult choices. We could offer more tuning to support difference performance vs. security and memory usage vs. security compromises though, and we could improve the existing tuning such as making the lightest slab quarantine setting much lighter by making the way it works a little bit less naive.

Essentially the only change beyond adding newer Android version support and dropping legacy support is preserving errno across `free` calls and that's to satisfy a **future** POSIX requirement rather than a current one, so it's not worth doing a release for it.

Help is wanted with adding features and some more tuning:

https://github.com/GrapheneOS/hardened_malloc/issues
