### ISSUE TITLE
Testing Under Archlinux - Works Well With Most Binaries

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/hardened_malloc#80]
I love what you're doing! I've been following your work since the previous OS that shall not be named.

On desktop Linux, the only issues I've seen are that Xorg refuses to start with the hardened malloc library preloaded, and man segfaults unless you disable seccomp for man with an application specific environment variable. Otherwise, even the dreaded systemd runs fine if an individual is insane enough to put the library in /etc/ld.so.preload.

For testing and production use, I plan on using it for internet facing applications on the desktop when not using Graphene on my phone. I've already found that hardened_malloc plays nice with the firejail seccomp sandbox - I wonder if firejail could somehow integrate this implementation and make it a baked in option someday?

Either way, for anyone else who wants to play with this on Arch:
https://aur.archlinux.org/packages/hardened-malloc-git/

**Comment by thestinger** [comment]
> and man segfaults unless you disable seccomp for man with an application specific environment variable

Does it actually hit a segmentation fault, or does it get killed for calling a system call that isn't permitted? It's quite possible that it adds a call to getrandom that wouldn't happen without it, resulting a violation of whatever seccomp-bpf policy they made, which is likely useless anyway.

> Otherwise, even the dreaded systemd runs fine if an individual is insane enough to put the library in /etc/ld.so.preload.

It's not really insane, it's just best to build it into the libc implementation rather than dynamically loading it and overriding the symbols.

**Comment by thestinger** [comment]
> and man segfaults unless you disable seccomp for man with an application specific environment variable

Does it actually hit a segmentation fault, or does it get killed for calling a system call that isn't permitted? It's quite possible that it adds a call to getrandom that wouldn't happen without it, resulting a violation of whatever seccomp-bpf policy they made, which is likely fairly useless and not part of a meaningful sandbox anyway.

> Otherwise, even the dreaded systemd runs fine if an individual is insane enough to put the library in /etc/ld.so.preload.

It's not really insane, it's just best to build it into the libc implementation rather than dynamically loading it and overriding the symbols.

**Comment by ilikenwf** [comment]
Behavior Below:

```LD_PRELOAD='/usr/lib/libhardened_malloc.so' man firejail                                                        [05/10 09:07 PM]
man: preconv: Bad system call (core dumped)
man: tbl: Bad system call (core dumped)
man: nroff: Bad system call (core dumped)
man: command exited with status 159: (cd /usr/share/man && /usr/lib/man-db/zsoelim) | (cd /usr/share/man && /usr/lib/man-db/manconv -f UTF-8:ISO-8859-1 -t UTF-8//IGNORE) | (cd /usr/share/man && preconv -e UTF-8) | (cd /usr/share/man && tbl) | (cd /usr/share/man && nroff -mandoc -rLL=142n -rLT=142n -Tutf8)
```

To build it into glibc would also require basically rebuilding the entire OS, which isn't feasible at the moment... that said, Xorg failing to start is the only thing holding me back from testing system wide, and suggesting that the Arch devs consider rolling it into glibc at some point.

**Comment by thestinger** [comment]
> Behavior Below:

Yeah, so it's not a segmentation fault, but rather you need to extend the system call whitelist, likely by adding getrandom to their whitelist and rebuilding it.

> To build it into glibc would also require basically rebuilding the entire OS, which isn't feasible at the moment

You don't need to rebuild the OS to build it into glibc, since nearly everything dynamically links against it.

> and at that point I'd suggest to the Arch maintainers that they consider rolling it into glibc at some point.

It probably wouldn't make sense in the default Arch Linux glibc since it's not a hardened distribution and wouldn't want to make the performance sacrifices, especially to have all the optional security features enabled (somewhat expensive) which is the default and how it's intended to be used.

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/hardened_malloc#system-calls. The only system call that wouldn't already be on their list is getrandom.

**Comment by ilikenwf** [comment]
Ah, that makes sense...on all counts.

I do wonder, though, if it may be a better balance to pick and choose the usage of libhardened_malloc, say with browsers and network facing applications, at the least. 

For desktops it may make sense, if integrated in glibc, to look for an env variable to turn on the hardened implementation, and otherwise default to the standard one.

**Comment by ilikenwf** [comment]
As an aside, the whitelist for man did fix it:

```
--- lib/sandbox.c	2019-01-05 03:08:56.000000000 -0600
+++ lib/sandbox.c	2019-05-31 15:27:10.923500188 -0500
@@ -502,6 +502,9 @@
 	SC_ALLOW ("sysinfo");
 	SC_ALLOW ("uname");
 
+	/* hardened_malloc syscalls */
+	SC_ALLOW ("getrandom");
+
 	/* Allow killing processes and threads.  This is unfortunate but
 	 * unavoidable: groff uses kill to explicitly pass on SIGPIPE to its
 	 * child processes, and we can't do any more sophisticated filtering


```
