### ISSUE TITLE
please upload your gpg key somewhere

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#82]
gpg --recv-keys 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
> gpg: keyserver receive failed: No data

The 3 most popular gpg keyservers web interfaces also don't show the key. Could you please upload somewhere?

**Comment by madaidan** [comment]
It works fine for me. The keyserver is probably being a bit slow. Try again.

**Comment by adrelanos** [comment]
No luck can try like 10 times and wait ages. If you "google" for just
the fingerprint in quotes (to specific results) you find multiple people
having this issue. Qubes just removed keyserver fetching for Qubes
builds due to unreliability.

I guess keyservers are death and won't come back (due to GDPR).

**Comment by thestinger** [comment]
https://github.com/thestinger.gpg

> The 3 most popular gpg keyservers web interfaces also don't show the key. Could you please upload somewhere?

It's definitely on them, but GPG keyservers are garbage, just like GPG itself. Maybe a denial of service is going on at the moment.

**Comment by thestinger** [comment]
By the way, for hardened_malloc, I would recommend using master right now. The (signed) tags are really GrapheneOS tags rather than hardened_malloc tags. I haven't done a stable release of it yet but making a v1 release is upcoming.

**Comment by adrelanos** [comment]
Daniel Micay:
> By the way, for hardened_malloc, I would recommend using master right now. The (signed) tags are really GrapheneOS tags rather than hardened_malloc tags. I haven't done a stable release of it yet but making a v1 release is upcoming.
> 

Good to know. hardened_malloc was added to Whonix wiki.

https://www.whonix.org/wiki/Whonix-Workstation_Security#hardened_malloc

(Might be moved to another Whonix wiki page.)

Could you sign your future git commits please?

**Comment by thestinger** [comment]
I wouldn't use the last GrapheneOS tag because you'll be missing https://github.com/GrapheneOS/hardened_malloc/commit/bc75c4db7bfa9ef095ec49d87b2f98f9f6d16198 which is a fix for a compatibility issue. It's rare for applications / libraries to use 0 byte allocations and code using them like this isn't portable but it's still technically correct and it shouldn't be detected as a memory corruption bug which is what was happening. The GrapheneOS tags are also meant for GrapheneOS and can have changes that are not intended to be used elsewhere.

In the future, I would recommend using the tagged releases, but there hasn't been an initial version 1 release of the hardened_malloc project yet. The advice to use master is temporary and only applies for perhaps another week. It's ready for the initial release, but I want to choose a good name for it rather than just calling it hardened_malloc which is the only thing delaying it.

> Could you sign your future git commits please?

Git signing is insecure and increasingly problematic, so I don't want to dig this hole any deeper. I'm planning on moving away from it for signing GrapheneOS source releases. I don't want to start using it more broadly because I want to replace all of the GPG usage. A signed commit or tag only has a signature on the commit or tag object. It verifies everything else via sha1 hash chains, all the way back to the root commit (not via signatures, even if they are present for every commit). This also means that Git exposes a massive amount of attack surface leading up to verifying the signature, and it does a very poor job of countering a malicious adversary in practice.

**Comment by thestinger** [comment]
It's also important to note that this is meant to be used alongside compiler (such as Clang type-based CFI) and standard C library hardening. It's intended to be built into the standard C library to use it globally and to enable using the API extensions within libc itself. This is the commit adding it to Bionic: https://github.com/GrapheneOS/platform_bionic/commit/20160b81611d6f2acd9ab59241bebeac7cf1d71c. It's a drop-in replacement for the malloc API in Bionic, musl and glibc so it's straightforward. You can see in https://github.com/GrapheneOS/platform_bionic that there's other hardening, but Bionic has a lot of this upstream now so there's less to do than there was before and I also haven't added everything back yet as it mentions in the repository description.

At some point, I'd like to make a similar hardened variant of musl for use on servers and in containers, etc. with the hardened_malloc, cross-DSO CFI and SafeStack support, setjmp hardening (beyond what glibc does), function pointer protection, secondary stack protection, etc. included. If you can find someone people interested in working on making a hardened musl integrating hardened_malloc and other changes, I would be interested in guiding them. Even though musl is missing some hardening that's in glibc it's a much better starting point due to simplicity and correctness in many cases that in glibc are buggy or reduce security with unnecessary complexity.

If you look at `/proc/PID/maps` or use this test program (https://github.com/GrapheneOS/hardened_malloc/blob/master/test/offset.c) you can see it makes a dedicate region with a high entropy base for each size class, and adds randomly sized guard regions around large allocations (>128k by default, or >16k if extended size classes are disabled). This is also something that should be done for other uses of mmap, such as secondary stacks.

As an alternative, it's also possible to to link every executable against it or it can be added to `/etc/ld.so.preload` which will preload it globally. Using `LD_PRELOAD` isn't recommended for that because it won't work across security boundaries where `AT_SECURE` is set including setuid binaries which are some of the most important places to use it.

**Comment by thestinger** [comment]
Oh and one more thing is that some programs include seccomp filters without `getrandom` and you'll need to add it for those to work. In many cases, these filters don't provide any actual sandbox, and it's not much more than security theatre, but I'd still recommend fixing their whitelists instead of disabling it. One example is the `man` tools.
