### ISSUE TITLE
consider adding -g flag to g++

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#88]
Last lintian warning.

```
W: hardened-malloc-dbgsym: debug-file-with-no-debug-symbols usr/lib/debug/.build-id/72/82c99d1cfb70edac107d9e7f243331e64f2622.debug
N: 
N:    The binary is installed as a detached "debug symbols" ELF file, but it
N:    does not appear to have debug information associated with it.
N:    
N:    A common cause is not passing -g to GCC when compiling.
N:    
N:    Implementation detail: Lintian checks for the ".debug_line" and the
N:    ".debug_str" sections. If either of these are present, the binary is
N:    assumed to contain debug information.
N:    
N:    Refer to https://bugs.debian.org/668437 for details.
N:    
N:    Severity: normal, Certainty: possible
N:    
N:    Check: binaries, Type: binary, udeb
```

Adding `-g` to `CPPFLAGS` fixed this lintian warning.

Does adding `-g` make sense or has this adverse effects?

**Comment by thestinger** [comment]
> Does adding -g make sense or has this adverse effects?

It would add compilation time and massively increase the unstripped binary size compared to not including all that debugging information.

It's possible that Debian passes this via CFLAGS, but it's not currently starting from CFLAGS in the environment. Try changing the CFLAGS line in the Makefile to be `CFLAGS := $(CFLAGS) [existing content]` so that it starts from passed in flags but then overrides them. It could do that for CPPFLAGS, CFLAGS, CXXFLAGS and LDFLAGS and it may resolve a lot of the issues you're running into. It does already start from the standard OS build flags for the Android build.

**Comment by adrelanos** [comment]
That worked amazing!

Created https://github.com/GrapheneOS/hardened_malloc/pull/91 for it.

That solved:

* https://github.com/GrapheneOS/hardened_malloc/issues/85
* https://github.com/GrapheneOS/hardened_malloc/issues/88 (this)

Not solved:

* https://github.com/GrapheneOS/hardened_malloc/issues/86

**Comment by thestinger** [comment]
Great, I'd rather not add `-g` to the standard flags so this is a nice approach for it.

**Comment by thestinger** [comment]
Some other things may still be worth addressing but in general it's nice to start from whatever the distribution wants and override it. I just wasn't really thinking about this case before as the `Makefile` build was largely for development / testing only since my focus was on GrapheneOS which uses the declarative `Android.bp` and inherently respects the OS build flags with how it sets flags.
