### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#89]
I am working on this.

**Comment by adrelanos** [comment]
It's done.

forked source code:
https://github.com/Whonix/hardened_malloc

The software fork homepage for Hardened Malloc, with a focus on easy installation, added user documentation, and integration with Whonix, Kicksecure, Debian, and other distributions:
https://www.whonix.org/wiki/Hardened_Malloc

Thank you very much for providing Hardened Malloc, even GrapheneOS-unspecific releases!

**Comment by thestinger** [comment]
@adrelanos Maybe you can get the man-db maintainers to add `getrandom` to their seccomp-bpf filter since that's the only case of breakage that I know about at the moment. The `getrandom` system call is also used by various other libc hardening, although they might not do anything that would trigger it. The reason this calls `getrandom` after initialization is to reseed the per-size-class CSPRNGs occasionally as a minor security enhancement. If I had a way to detect that it would kill the process, I could just not do it, but it would be best if people just didn't blacklist `getrandom` when they're using `malloc` because hardened allocators should be allowed to use it.

**Comment by adrelanos** [comment]
Created https://savannah.nongnu.org/bugs/index.php?56767 for it.

**Comment by adrelanos** [comment]
Adding `/usr/lib/libhardened_malloc.so/libhardened_malloc.so` to `/etc/ld.so.preload` makes (Qubes) Debian (not sure which one I tested) unusable for me. Are issues (with X?) like this a known issue or something you would be interested in debugging and fix?

**Comment by thestinger** [comment]
@adrelanos For the man-db issue, it's also worth noting that the intention is for hardened_malloc to be integrated into libc so detecting that it's preloaded wouldn't be a good way of handling the need to whitelist `getrandom`. Preloading it via `/etc/ld.so.preload` is perfectly safe. However, in a locked down system with meaningful verified boot that kind of mutable global configuration doesn't exist, so it has to be in libc.

It's unlikely that any issues you encounter are the fault of hardened_malloc since it's already successfully deployed for GrapheneOS and the kinks should already be worked out. C and C++ software has pervasive memory corruption bugs to the point that there's even a lot of latent memory corruption occurring during regular usage, without even hitting any edge cases. It should be expected that bugs are going to be uncovered by the mitigations.

I currently need to disable some of the security features for the camera driver on the Pixel 3: https://github.com/GrapheneOS/hardened_malloc/commit/2ed5d2edaade92ee2a3d91a60b629e1d05119beb. I previously had to do this for the citadel driver (driver for the Titan M HSM) too, but [that was fixed a couple months ago](https://android.googlesource.com/platform/external/nos/host/android/+/2b2d7642e9d05d1f6768d22ae437e5de2003d04d%5E%21/#F0). I have too little time to investigate and resolve all of these issues myself even for GrapheneOS. I generally take a look at it and then just work around it temporarily, and I try to either file a report upstream about the memory corruption bug or get someone else to do it.

The desktop Linux software stack isn't nearly as heavily tested with ASan as the Android Open Source Project and has much more C and C++ code as opposed to memory safe languages so you should expect to hit more of these issues than I do. I've tested some software already and found memory corruption bugs in WebKitGTK among other places. I was doing this to test hardened_malloc and after verifying that each of the issues was caused by the software, I just moved on, since I can't take on the responsibility of fixing everything across all these projects.

There's a good chance of uncovering the same issue by building the software with either the Clang or GCC implementation of ASan. You can report all the bugs uncovered by ASan upstream and since it's oriented towards debugging rather than hardening it provides detailed error output, stack traces, etc. The approach in hardened_malloc aims to break exploits and that often means latent memory corruption bugs will intentionally lead to an abort or segmentation fault, often in a way that's ridiculously hard to debug because it's not instrumenting the code and storing stack traces for each allocation like ASan. I would recommend looking at what kind of crash occurs (abort vs. segmentation fault, etc.) and perhaps trying with a configuration of hardened_malloc friendlier to memory corruption. The majority of these issues end up being use-after-free bugs and disabling these two features has a good chance of allowing the memory corruption to happen without an abort / fault / other failure:

```
CONFIG_ZERO_ON_FREE := true
CONFIG_WRITE_AFTER_FREE_CHECK := true
```

If disabling these sidesteps the problem, it's almost certainly a use-after-free bug in the software. You can usually detect it with ASan though, at least if the ASan quarantine is configured to be large enough. Zero on free and the write after free check are very important core security features so I'd only recommend doing this for testing. The reason for offering configuration is the relatively high performance cost, and I also like being able to test the performance of these optional security features. It's nice to be able to disable all of them and test the performance of the core allocator design, which is quite competitive (aside from lack of thread caching) despite the security-oriented design. Also, even with these 2 features disabled, use-after-free bugs can still get caught by the memory protection features. These features are only used for small slab allocations and work together with the quarantine. For large allocations, they get purged / memory protected on free with the fresh PROT_NONE mapping held in the quarantine to trigger faults on any invalid accesses for as long as possible (until the allocator is forced to release it from the quarantine due to memory being needed elsewhere, essentially).

As another example, the Qt ecosystem is full of type confusion bugs detected by the sanity checks in the C++ allocator implementation, so that can be worked around by disabling `CONFIG_CXX_ALLOCATOR`. Unlike zero-on-free and the write after free check, disabling that isn't a big deal. The feature *does* detect type confusion bugs in actual real world attacks, but it doesn't have nearly as much value. Most of the latent bugs it will uncover are relatively harmless undefined behavior, they are definitely bugs, but they don't usually involve actual memory corruption. The zero-on-free / write after free check features won't catch anything that's not serious memory corruption. Many of the issues aren't going to be vulnerabilities, but I think any memory corruption bug can be considered quite serious. Accessing memory after it's freed is a serious problem.

**Comment by cjwatson** [comment]
man-db maintainer here.  I'm happy to allow `getrandom`, although I won't be able to get to it until next week.

**Comment by adrelanos** [comment]
Recently a discussion was started on hardened malloc which I would like to make you aware of.
`[tor-dev] TBB Memory Allocator choice fingerprint implications`
https://lists.torproject.org/pipermail/tor-dev/2019-August/013977.html

thread view:
https://lists.torproject.org/pipermail/tor-dev/2019-August/thread.html#13977

subject view:
https://lists.torproject.org/pipermail/tor-dev/2019-August/subject.html#13977

also a ticket which I created recently:
https://trac.torproject.org/projects/tor/ticket/31440

**Comment by cjwatson** [comment]
man-db fixed: https://git.savannah.gnu.org/cgit/man-db.git/commit/?id=0951f82c611c4a3c14271b0fa9c4919c84b7afe7

**Comment by thestinger** [comment]
@cjwatson Thanks! If man-db spawns threads inside the sandbox, that's another case where `getrandom` would potentially be called by a hardened libc implementation, as part of secondary stack randomization. I ran into this with OpenBSD malloc and secondary stack randomization with Android's media seccomp sandboxes a while ago:

https://android.googlesource.com/platform/frameworks/av/+/2dde5ecefdf2691bdced553e4dfc276da1d9c17e%5E%21/

In that case, it was triggered by the arc4random reseed, and hardened_malloc essentially has an arc4random implementation with ChaCha8 instead of ChaCha20 for each size class within each arena for performance reasons.

**Comment by cjwatson** [comment]
man-db doesn't spawn threads, no.

**Comment by cjwatson** [comment]
Well, actually, to be fair it's possible that some decompressor implementations called by man-db will use threads; IIRC xz sometimes does.

**Comment by adrelanos** [comment]
[RFP: hardened-malloc -- hardened memory allocator](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945455)

**Comment by adrelanos** [comment]
[glibc feature request - consider using Hardened Malloc](https://sourceware.org/bugzilla/show_bug.cgi?id=25223)

[debian glibc feature request - consider using hardened malloc (hardened memory allocator)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945457)

**Comment by adrelanos** [comment]
[glibc-alpha mailing list - consider using Hardened Malloc](https://sourceware.org/ml/libc-alpha/2019-11/msg00810.html)

**Comment by adrelanos** [comment]
Updating Debian packaging for Debian bullseye...

Would you recommend llvm-9 or llvm-11? (These are the only avaialble versions in Debian bullseye repository.) @thestinger

**Comment by thestinger** [comment]
Most recent is best. It's only really developed against the latest stable releases and then fixes are done for older releases.

**Comment by thestinger** [comment]
On that note, we really need to find a developer for us to fund to implement memory tagging support for ARMv8.4 / ARMv9. It's the main thing that's needed and there isn't really that much to do of great importance beyond it. This would ideally be developed via the QEMU MTE support before the hardware is available at which point we'll be behind. hardened_malloc could make much better use of memory tagging than other allocators.

**Comment by adrelanos** [comment]
> On that note, we really need to find a developer for us to fund to implement memory tagging support for ARMv8.4 / ARMv9. It's the main thing that's needed and there isn't really that much to do of great importance beyond it. This would ideally be developed via the QEMU MTE support before the hardware is available at which point we'll be behind. hardened_malloc could make much better use of memory tagging than other allocators.

May I kindly recommend to create a dedicated ticket for this? If there was one, I'd be happy to share this in Whonix usual outreach channels, social media.

**Comment by thestinger** [comment]
I don't think I want to handle packaging stuff upstream but rather we can make changes to the Makefile if needed to provide better support for something that's needed.
