### ISSUE TITLE
gcc vs clang - preference? security impact?

### ISSUE THREAD

**Issue by adrelanos** [GrapheneOS/hardened_malloc#94]
I am currently compiling using gcc.

https://github.com/GrapheneOS/hardened_malloc/issues/89#issuecomment-521520623

It would be possible to switch to clang.

Is any of these two preferred, to be expected more/less reliable, secure, suitable, performance, whatsoever?

**Comment by thestinger** [comment]
I don't think it will make much difference for only hardened_malloc in isolation. Overall, I would definitely recommend using Clang in order to make use of type-based Control Flow Integrity, ShadowCallStack on arm64 or SafeStack as a more portable alternative, and the ability to use UBSan sanitizers in trapping for mode production. On Pixels, even the Linux kernel is compiled with Clang to get type-based Control Flow Integrity and soon ShadowCallStack. GrapheneOS improves this a bit by getting rid of dynamic kernel module support which is not useful other than as a boot time optimization to load some code asynchronously since the kernels are specialized builds with minimal attack surface. Having a fully static build makes the CFI analysis better.

Of these features, GCC does have UBSan, but not in a production quality state like Clang. Not all the UBSan sanitizers are worth using for hardening, but it does make sense to use the integer sanitizers. If you look in the Makefile you'll see I use UBSan in the debug mode for testing already (`CONFIG_UBSAN`) but I don't think you'll really get anything out of it for this case in production. The main use for it as hardening is `-fsanitize=integer` which does both signed integer overflow checking (which is undefined + always a bug) and unsigned integer overflow checking (not included in -fsanitize=undefined) which requires adapting the code to mark all intended overflows. I haven't yet added compatibility with unsigned integer overflow checking here anyway, largely because of code outside my control (libdivide) which gets pulled in via a header. It won't be extremely useful here since I'm been extremely careful about checking all the overflow cases. It would be useful to use it for testing / fuzzing though.

**Comment by thestinger** [comment]
Worth noting that the full support for building the Linux kernel with Clang is not yet upstream, and neither are CFI, Clang LTO (prerequisite for CFI) and ShadowCallStack. It should be landing in the near future... but the upstream developers have been very resistant to supporting other compilers and to security features in general too.

**Comment by adrelanos** [comment]
Alright, clang then.

```
make CC=clang
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o chacha.o chacha.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o h_malloc.o h_malloc.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o memory.o memory.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o pages.o pages.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o random.o random.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o util.o util.c
warning: unknown warning option '-Wcast-align=strict'; did you mean '-Wcast-align'? [-Wunknown-warning-option]
1 warning generated.
g++ -std=c++14 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native  -D_GNU_SOURCE -DZERO_ON_FREE=true -DWRITE_AFTER_FREE_CHECK=true -DSLOT_RANDOMIZE=true -DSLAB_CANARY=true -DSLAB_QUARANTINE_RANDOM_LENGTH=1 -DSLAB_QUARANTINE_QUEUE_LENGTH=1 -DCONFIG_EXTENDED_SIZE_CLASSES=true -DCONFIG_LARGE_SIZE_CLASSES=true -DGUARD_SLABS_INTERVAL=1 -DGUARD_SIZE_DIVISOR=2 -DREGION_QUARANTINE_RANDOM_LENGTH=128 -DREGION_QUARANTINE_QUEUE_LENGTH=1024 -DREGION_QUARANTINE_SKIP_THRESHOLD=33554432  -DFREE_SLABS_QUARANTINE_RANDOM_LENGTH=32 -DCONFIG_CLASS_REGION_SIZE=34359738368  -DN_ARENA=4 -DCONFIG_STATS=false  -c -o new.o new.cc
clang  -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align=strict -Wcast-qual -Wwrite-strings -march=native -Wmissing-prototypes  -Wl,-soname=libhardened_malloc.so,--as-needed,-z,defs,-z,relro,-z,now,-z,nodlopen,-z,text -shared chacha.o h_malloc.o memory.o pages.o random.o util.o new.o -lstdc++ -o libhardened_malloc.so
/usr/bin/ld: new.o: plugin needed to handle lto object
```

Is this output expected?

It mostly uses clang, however... Is it expected/ok/good that `g++` is used once?

**Comment by thestinger** [comment]
Set `CXX=clang++` too or you'll hit that LTO error from trying to mix them. It's expected that it gives that annoying warning because Clang gives warnings on unknown warnings instead of errors so the code to detect whether `-Wcast-align=strict` is supported doesn't properly fall back. I guess the safe_flag function in the Makefile could be tweaked to consider having any stderr output to be a failure.

**Comment by thestinger** [comment]
@adrelanos By the way, I got rid of that Clang warning:

https://github.com/GrapheneOS/hardened_malloc/commit/cc8c4459e1147857b5e917e1c2744e442935fd57
https://github.com/GrapheneOS/hardened_malloc/commit/1bc201c4c179a3ddb8d12735d78e15265b99f5e4

The issue is that Clang doesn't support arguments to `-Wcast-align` and treats `-Wcast-align=strict` as an unknown warning flag. Working around this was mildly useful beyond silencing the warning since now Clang has `-Wcast-align` passed to it.

**Comment by thestinger** [comment]
@adrelanos I also prevented the potential to make the mistake of setting `CC` without `CXX`:

https://github.com/GrapheneOS/hardened_malloc/commit/8d2df1deb8ddf2965dba5859ff9c8cf8dc1ef42d

Once you have this commit, there's no need to pass `CXX` since it will just be overridden.

**Comment by adrelanos** [comment]
`make CC=clang` fails for me with exit code `2`.

> clang -g -O2 -fdebug-prefix-map=/build/hardened-malloc-0.4=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O3 -flto -fPIC -fvisibility=hidden -fno-plt  -fstack-protector-strong -pipe -Wall -Wextra -Wcast-align -Wcast-qual -Wwrite-strings -Werror -Wmissing-prototypes -Wl,-z,relro -Wl,-z,now -Wl,--as-needed,-z,defs,-z,relro,-z,now,-z,nodlopen,-z,text -shared chacha.o h_malloc.o memory.o pages.o random.o util.o new.o -lstdc++ -shared-libgcc -o libhardened_malloc.so
clang: error: argument unused during compilation: '-shared-libgcc' [-Werror,-Wunused-command-line-argument

**Comment by thestinger** [comment]
@adrelanos I guess it wasn't supported in old versions of Clang. It's difficult to work around outdated toolchain versions and the differences between Clang / GCC are quite annoying. I'm used to only needing to support Clang.

**Comment by thestinger** [comment]
@adrelanos Try again with the latest change: https://github.com/GrapheneOS/hardened_malloc/commit/58b56f10eae3a16d34ac4123f56fa90c8100cce6.

**Comment by adrelanos** [comment]
That works perfectly!
